"""Tests for the first-run tutorial and Excel export (CLAUDE.md section 7
and section 6's export). Drives the real app.py via AppTest, same as
tests/test_app_reactivity.py -- these interactions live entirely in app.py,
with no separate testable module.
"""

import io

import pandas as pd
import pytest
from streamlit.testing.v1 import AppTest

from src import copy


def _fresh_app():
    at = AppTest.from_file("../app.py")
    at.run(timeout=30)
    assert not at.exception
    return at


def test_welcome_panel_shows_on_first_load():
    at = _fresh_app()
    assert at.session_state["show_welcome"] is True
    labels = [b.label for b in at.button]
    assert copy.WELCOME_DISMISS_BUTTON in labels
    assert copy.WELCOME_EXAMPLE_BUTTON in labels


def test_got_it_dismisses_the_panel():
    at = _fresh_app()
    got_it = next(b for b in at.button if b.label == copy.WELCOME_DISMISS_BUTTON)
    got_it.click().run(timeout=30)

    assert not at.exception
    assert at.session_state["show_welcome"] is False


def test_reopen_button_shows_the_panel_again_after_dismissal():
    at = _fresh_app()
    next(b for b in at.button if b.label == copy.WELCOME_DISMISS_BUTTON).click().run(timeout=30)
    assert at.session_state["show_welcome"] is False

    next(b for b in at.button if b.label == copy.WELCOME_REOPEN_BUTTON).click().run(timeout=30)
    assert not at.exception
    assert at.session_state["show_welcome"] is True


def test_show_me_an_example_adds_a_demo_scenario_with_a_battle_pass_uplift():
    at = _fresh_app()
    example = next(b for b in at.button if b.label == copy.WELCOME_EXAMPLE_BUTTON)
    example.click().run(timeout=30)

    assert not at.exception
    assert at.session_state["show_welcome"] is False

    demo = at.session_state["scenarios"][copy.WELCOME_EXAMPLE_SCENARIO_NAME]
    assert len(demo.uplifts) == 1
    assert demo.uplifts[0].note == copy.WELCOME_EXAMPLE_UPLIFT_NOTE

    table = at.dataframe[0].value
    assert copy.WELCOME_EXAMPLE_SCENARIO_NAME in table["Scenario"].tolist()


def test_export_button_present_with_correct_label():
    at = _fresh_app()
    downloads = at.get("download_button")
    assert len(downloads) == 1
    assert downloads[0].label == copy.EXPORT_BUTTON_LABEL


def test_export_table_is_readable_excel_with_numeric_columns():
    # Mirrors app.py's export construction directly (AppTest doesn't expose
    # a download button's generated bytes), proving the pandas/openpyxl
    # round trip actually produces numbers a spreadsheet can sum or chart,
    # not pre-formatted text like the on-screen table.
    from src.charts import display_name
    from src.model import fit_model, load_history
    from src.scenarios import Scenario, compare_scenarios, run_scenario

    fitted = fit_model(load_history())
    results = [run_scenario(fitted, Scenario("Plan", [fitted.last_spend] * 12))]
    rows = compare_scenarios(results, baseline_name="Plan")

    export_table = pd.DataFrame(
        [
            {
                "Scenario": display_name(r),
                copy.HEADLINE_TOTAL_REVENUE: row.total_revenue,
                copy.CHART_DRIVERS_BASE_LABEL: float(r.base_business.sum()),
            }
            for r, row in zip(results, rows)
        ]
    )
    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
        export_table.to_excel(writer, index=False, sheet_name="Comparison")
    buffer.seek(0)

    read_back = pd.read_excel(buffer, sheet_name="Comparison")
    assert read_back[copy.HEADLINE_TOTAL_REVENUE].dtype.kind == "f"
    assert read_back[copy.HEADLINE_TOTAL_REVENUE].iloc[0] == pytest.approx(results[0].total_revenue)
