"""Tests for the first-run tutorial and Excel export (CLAUDE.md section 7
and section 6's export). Drives the real app.py via AppTest, same as
tests/test_app_reactivity.py -- these interactions live entirely in app.py,
with no separate testable module.
"""

import io

import pandas as pd
import pytest
from streamlit.testing.v1 import AppTest

from src import copy


def _fresh_app():
    at = AppTest.from_file("../app.py")
    at.run(timeout=30)
    assert not at.exception
    return at


def test_welcome_panel_shows_on_first_load():
    at = _fresh_app()
    assert at.session_state["show_welcome"] is True
    labels = [b.label for b in at.button]
    assert copy.WELCOME_DISMISS_BUTTON in labels
    assert copy.WELCOME_EXAMPLE_BUTTON in labels


def test_got_it_dismisses_the_panel():
    at = _fresh_app()
    got_it = next(b for b in at.button if b.label == copy.WELCOME_DISMISS_BUTTON)
    got_it.click().run(timeout=30)

    assert not at.exception
    assert at.session_state["show_welcome"] is False


def test_reopen_button_shows_the_panel_again_after_dismissal():
    at = _fresh_app()
    next(b for b in at.button if b.label == copy.WELCOME_DISMISS_BUTTON).click().run(timeout=30)
    assert at.session_state["show_welcome"] is False

    next(b for b in at.button if b.label == copy.WELCOME_REOPEN_BUTTON).click().run(timeout=30)
    assert not at.exception
    assert at.session_state["show_welcome"] is True


def test_show_me_an_example_populates_the_draft_not_a_saved_scenario():
    # Previously this button added a new *saved* scenario, invisible unless
    # you scrolled to the comparison table -- the sidebar (budget table,
    # initiatives table) stayed completely blank, so it looked like the
    # button did nothing. Fixed to populate the draft directly: the same
    # tables she'd edit herself.
    at = _fresh_app()
    assert at.session_state["draft_budget"] == [0] * 12  # sanity: starts blank

    example = next(b for b in at.button if b.label == copy.WELCOME_EXAMPLE_BUTTON)
    example.click().run(timeout=30)

    assert not at.exception
    assert at.session_state["show_welcome"] is False

    # The sidebar's own budget table changed -- not a separate saved scenario.
    assert at.session_state["draft_budget"] != [0] * 12
    assert all(b > 0 for b in at.session_state["draft_budget"])
    assert "scenarios" not in at.session_state or set(at.session_state["scenarios"].keys()) == {
        "Conservative",
        "Plan",
        "Aggressive",
    }

    uplifts_df = at.session_state["draft_uplifts_df"]
    assert len(uplifts_df) == 1
    assert uplifts_df.iloc[0][copy.INITIATIVES_NOTE_COLUMN] == copy.WELCOME_EXAMPLE_UPLIFT_NOTE
    assert uplifts_df.iloc[0][copy.INITIATIVES_MODE_COLUMN] == copy.UPLIFT_MODE_PERMANENT

    # And the chart's draft line reflects it -- no longer flat at the
    # baseline-only trajectory a zero budget would produce.
    table = at.dataframe[0].value
    draft_row = table[table["Scenario"].str.contains("Current plan")].iloc[0]
    assert draft_row[copy.HEADLINE_TOTAL_SPEND] != "€0"


def test_export_button_present_with_correct_label():
    at = _fresh_app()
    downloads = at.get("download_button")
    assert len(downloads) == 1
    assert downloads[0].label == copy.EXPORT_BUTTON_LABEL


def test_export_columns_match_the_on_screen_comparison_table():
    # The Excel export previously omitted "Monthly budget" after it was
    # added to the on-screen table -- the two were built independently and
    # drifted. app.py now asserts this on every run, so a fresh drift
    # crashes the app immediately instead of shipping a silently-missing
    # column. Drives the real app.py (not a hand-copy of its table
    # construction, which could drift independently of the real code and
    # pass even when app.py itself is broken -- confirmed by mutation
    # testing this exact scenario) and checks the comparison table's own
    # columns against the export contract app.py enforces on itself.
    at = _fresh_app()
    table_columns = list(at.dataframe[0].value.columns)

    expected_export_columns = [
        "Scenario",
        copy.HEADLINE_TOTAL_REVENUE,
        copy.HEADLINE_TOTAL_SPEND,
        copy.HEADLINE_MONTHLY_BUDGET_COLUMN,
        copy.HEADLINE_REVENUE_PER_SPEND,
        copy.HEADLINE_VS_BASELINE,
        copy.CHART_DRIVERS_BASE_LABEL,
        copy.CHART_DRIVERS_MARKETING_LABEL,
        copy.CHART_DRIVERS_INITIATIVES_LABEL,
    ]
    assert table_columns == expected_export_columns
    # app.py's own runtime assert (see app.py, right after export_table is
    # built) is what actually guards export_table against drifting from
    # this list -- at.exception being empty here is that guard passing.
    assert not at.exception


def test_export_table_is_readable_excel_with_numeric_columns():
    # Mirrors app.py's export construction directly (AppTest doesn't expose
    # a download button's generated bytes), proving the pandas/openpyxl
    # round trip actually produces numbers a spreadsheet can sum or chart,
    # not pre-formatted text like the on-screen table.
    from src.charts import display_name
    from src.model import fit_model, load_history
    from src.scenarios import Scenario, compare_scenarios, run_scenario

    fitted = fit_model(load_history())
    results = [run_scenario(fitted, Scenario("Plan", [fitted.last_spend] * 12))]
    rows = compare_scenarios(results, baseline_name="Plan")

    export_table = pd.DataFrame(
        [
            {
                "Scenario": display_name(r),
                copy.HEADLINE_TOTAL_REVENUE: row.total_revenue,
                copy.CHART_DRIVERS_BASE_LABEL: float(r.base_business.sum()),
            }
            for r, row in zip(results, rows)
        ]
    )
    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
        export_table.to_excel(writer, index=False, sheet_name="Comparison")
    buffer.seek(0)

    read_back = pd.read_excel(buffer, sheet_name="Comparison")
    assert read_back[copy.HEADLINE_TOTAL_REVENUE].dtype.kind == "f"
    assert read_back[copy.HEADLINE_TOTAL_REVENUE].iloc[0] == pytest.approx(results[0].total_revenue)
